FC=mpif90
FLAGS= -c -O2 -fallow-argument-mismatch -ffree-line-length-none -Wno-line-truncation
LF = -llapack -lblas
HOME = ../lib/package_of_matrix
LIBS= $(HOME)/Modules/modules_90.a \
      $(HOME)/MyEis/libeis.a \
      $(HOME)/MyNag/libnag.a \
      $(HOME)/MyLin/liblin.a \
      $(HOME)/Ran/libran.a $(LF)
all:
	cp $(HOME)/Modules/*.mod . ;\
	(make -f Compile FC="$(FC)" LF="$(LF)" FLAGS="$(FLAGS)" LIBS="$(LIBS)" SUFFIX="")
clean: 	
	(make -f Compile clean );\
	rm -f *.mod
